import express from "express";
import { listChats, createOrGetChat, getChatById, sendMessageToChat, deleteChat } from "../controllers/chatController.js";
import { protect } from "../middleware/authMiddleware.js";
const router = express.Router();
router.get("/", protect, listChats);
router.post("/", protect, createOrGetChat);
router.get("/:chatId", protect, getChatById);
router.post("/:chatId/messages", protect, sendMessageToChat);
router.delete("/:chatId", protect, deleteChat);
export default router;
